### PR TITLE
Add support for JSONQL (issue #31).

### PR DESCRIPTION
**Pull request by ShaheedHaque**
I added support for the JSONQL 'driver' setting and the corresponding 'json_query' in the db_connections, a sample jsonql.jrxml file, as well as some supporting text in the README.rst file.

Please consider.

### CODE REVIEW

**Comment by jadsonbr** [comment]
@ShaheedHaque Could you please write your routine test first?

**Comment by ShaheedHaque** [comment]
@jadsonbr I have a test written but it won't pass without the updated jasperstarter, so I did not commit it yet. Upstream has merged their [side of the change](https://bitbucket.org/cenote/jasperstarter/commits/2cac5f4302793c4c5b9d33c4fb42805faff4e643) so I believe their CI builds now have the change, but they have obviously not released it.

I could push the failing new test? Can you advise how you wish me to proceed?

BTW, the subreports test fails for me (before and after this change).

**Comment by ShaheedHaque** [comment]
The second commit is because I forgot to undo a test-related change in the jrxml. The dip in coverage (not sure why it was not reported before?) is due to the 1-line now not tested; that will be covered by the test I have written.

**Comment by ShaheedHaque** [comment]
Upstream has said they plan to release with JasperReports 6.5.1 "in the next days". I suggest that if you were able to pull that in, I could then add the tests to this PR, and then you could consider the merge with (hopefully :-)) the coverage issue solved.

**Comment by jadsonbr** [comment]
As soon as I have available I update and I accept the PR

**Comment by ShaheedHaque** [comment]
Great. If you could kindly let me know after you get the jasperstarter update (I will also try to keep watch), I will then add the tests to this PR. They should then pass (or I will fix them!), and then we'll be ready to merge.

**Comment by ShaheedHaque** [comment]
I pushed the test, even though it fails without the support from upstream jasperstarter. I did this because the promised release from upstream has not happened, and I did not want to end up losing the code (e.g. by mistake). Clearly, this PR is now not mergable before the upstream support arrives.

**Comment by ShaheedHaque** [comment]
@jadsonbr I've been working with upstream to get a new release out, and so there is now a [3.3 download with JSONQL support needed by this issue](https://sourceforge.net/projects/jasperstarter/files/). It also has JasperReports 6.7. Pulling that should allow this PR to pass its tests, so please do consider integrating 3.3 and then merging this PR.

**Comment by jadsonbr** [comment]
I'll be watching this week

**Comment by jadsonbr** [comment]
Done

**Comment by ShaheedHaque** [comment]
Many thanks. I look forward to a release in due course :-).

**Pull request merged**
