### PR TITLE
Make pyreportjasper work with Open JDK15.   Added code to compile, fill and output jasper reports without needing to spawn a system process via jasperstarter.

### PR DESCRIPTION
**Pull request by davidlehrian**

### CODE REVIEW

**Comment by davidlehrian** [comment]
I wanted to mention that this solution requires that the JVM be initialized with the option -Djava.system.class.loader=org.update4j.DynamicClassLoader.  This is compiled into jasperstarter.exe because I modified the pom.xml file that builds the exe.  So the methods jasperpy.compile and jasperpy.process will work just fine because they rely on spawning a subprocess that runs jasperstarter.exe.  

However, for the methods that use jpy and therefore the JVM created via the jpyutil.init_jvm method, the option needs to be added to the jpyconfig.py file with the line jvm_options = ['-Djava.system.class.loader=org.update4j.DynamicClassLoader'].  As jpy isn't part of this code this change isn't part of the pull request, but it needs to be documented that this change is required in order to use the compile, load fill and generate methods that I added in pyjasperreports.  

The issue with jasperstarter not working with a JVM newer than Oracle JDK 8 has to do with dynamically adding the database jar files to the classpath at runtime.  JDK 8 had the method ClassLoader.getSystemClassLoader return a class loader that was subclassed from URLClassLoader and so classes could be added dynamically using reflection and calling URLClassLoader.addURL.  But JDK 9 and greater changed this inheritance so that the class loader return via ClassLoader.getSystemClassLoader is no longer subclassed from URLClassLoader and therefore this reflection call fails.  The option -Djava.system.class.loader=org.update4j.DynamicClassLoader change the classloader returned via ClassLoader.getSystemClassLoader to be org.update4j.DynamicClassLoader which is subclassed from URLClassLoader and therefore the database jar files can once again be dynamically added.  There is one other issue that is addressed in the changes I made to jasperstarter but the key change is to tell the JVM to use org.update4j.DynamicClassLoader as the system class loader.  

And as I was writing this I realized that I didn't make the change for the shell script that launches jasperstarter in linux.  I have made than change in my fork and will see how I add that change to this pull request.

**Comment by jadsonbr** [comment]
@davidlehrian If you can, create an example so we can update the documentation.

**Comment by davidlehrian** [comment]
Sure, I can add my jpyconfig.py to the PR.  Where do you think it would be most appropriate?  The examples folder didn't seem like the correct place so it would either be the root folder or the pyreportjasper folder.

**Comment by davidlehrian** [comment]
This is the full contents of my jpyconfig.py file:

# Created by 'jpyutil.py' tool on 2020-10-14 00:34:46.587802
# This file is read by the 'jpyutil' module in order to load and configure the JVM from Python
java_home = 'C:\\Program Files\\Java\\jdk-15'
jvm_dll = 'C:\\Program Files\\Java\\jdk-15\\bin\\server\\jvm.dll'
jvm_maxmem = None
jvm_classpath = []
jvm_properties = {}
jvm_options = ['-Djava.system.class.loader=org.update4j.DynamicClassLoader']

**Comment by jadsonbr** [comment]
@davidlehrian I believe we can send a PR to jpy to make it dynamic. If they delay, we can add a code to add this information to jpyconfig.py during the installation of pyreportjasper.

[Click here to see the line where the jpy file is generated](https://github.com/bcdev/jpy/blob/4d78ce261e6446862ef0b4ccfe39c5d395bf575a/jpyutil.py#L570)

**Comment by davidlehrian** [comment]
Well the only issue I see with jpy adding this to their project is they would need to add org.update4j.DynamicClassLoader to their project which would then become the default system class loader for EVERY installation.  Not sure this is the correct solution for everyone using jpy.  It is only needed when trying to add jar files dynamically to the system class path like jasperstarter is doing.  This is a dependency problem of jasperstarter on this custom version of jpy and I don't have a good recommendation/solution.

**Comment by davidlehrian** [comment]
Thinking about this org.update4j.DynamicClassLoader is included in my changes to jasperstarter so it would actually be during the installation of jasperstarter where this change to the jpyconfig.py file would need to be made.  So jasperstarter has jpy as an installation dependency and so after the successful installation of jpy, jasperstarter would need to modify this file.  That is actually the correct solution.

**Comment by davidlehrian** [comment]
So I realize my previous comment doesn't make sense.  jasperstarter isn't a python project hence the reason that the binary is included in your project pyreportjasper.  But the change to the jvm_options in jpyconfig.py only needs to be made when using jpy in the context of pyreportjasper and, unless org.update4j.DynamicClassLoader were included as part of jpy, the jvm_options would make jpy fail to run.  So I see two options: 1. include org.update4j.DynamicClassLoader in jpy along with the change to jpyconfig.py.  2. leave org.update4j.DynamicClassLoader in pyreportjasper and edit jpyconfig.py during the installation of pyreportjasper.

**Comment by davidlehrian** [comment]
So option 1 doesn't work because org.update4j.DynamicClassLoader is imported and used in Db.java and ApplicationClasspath.java, both part of jasperstarter.  So that leaves editing jpyconfig.py to add '-Djava.system.class.loader=org.update4j.DynamicClassLoader' to jvm_options during the installation of pyreportjasper.

**Comment by jadsonbr** [comment]
@davidlehrian In the current situation, you are only using the jasperstarter library to connect to the database

**Comment by davidlehrian** [comment]
I am using the dynamic jdbc jar loading of jasperstarter and I'm using the Jasper Reports jar files that jasperstarter includes.  I am not using JasperPy.compile and JasperPy.process as they spawn a subprocess to call jasperstarter which I found to be very slow.  That is where I had started out using this library.  Then I saw the techniques you used in JasperPy.process_json where you instantiated java objects directly via jpy and ran them 'in-process'.  That is when I added pyjasperreports.py which uses the same technique to perform the compile and fill functionality which I have found to provide much better performance.  I certainly could write this all myself, but I would have to redo the dynamic loading functionality in JasperStarter and the packaging that you have done and it seemed like this would be a good enhancement to this library.  I am currently in the process of deploying it to an AWS environment and I would rather keep moving forward than rewriting existing code.

**Comment by jadsonbr** [comment]
Yes, yes I am here looking at what you did and thinking about restructuring the library so that the jasperstarter is no longer needed. I will start writing these changes soon as soon as I do an analysis of the impacts

**Comment by davidlehrian** [comment]
Ah yes, after reviewing my code I see your point.  I am only using 3 objects from JasperStarter to create the database connection that gets passed to the report AND their code that loads the JDBC driver dynamically.  That was the code in their library that I had to modify to make work with OpenJDK 15 (which also works with Amazon Corretto 15 btw).  But I had to modify the wheel file anyway in order to include the JDBC driver for MySQL when I deployed the app.  It would be great to figure out a way to not need to modify the wheel file yet still point the java code to the JDBC directory.  Kind of like how JasperStarter has the command line option to specify the JDBC directory.  I'm not even sure what that would look like but I'll give it some thought.

**Comment by jadsonbr** [comment]
@davidlehrian  In fact you don't need to modify the wheel just pass the directory where your jar is or the path of the jar straight to the resource parameter.

[Here's how to work with resources](https://github.com/PyReportJasper/pyreportjasper/wiki/Working-with-resources)

**Comment by jadsonbr** [comment]
I'm also considering using jpype as it seems to be more consistent than jpy


[Github jpype](https://github.com/jpype-project/jpype/)

**Comment by davidlehrian** [comment]
@jadsonbr I like it.  Passing the JDBC driver location to the process method (or fill method in the case of the code I added) seems like a good solution as the DB parameters are being passed already.  This way the report could be filled by different databases if needed.  The only thing that will need to be handled would be a check to see if the driver is already loaded before attempting to load it again from the jar file which is a simple check.  

Regarding jpype, I don't have any experience with it, but if they are more responsive than the folks at jpy it would be a reasonable solution.  Just glancing at their GitHub page I see they support OpenJDK, Oracle and Corretto 8, 9 and 11.  I wonder why they don't support the latest version 15?

**Comment by jadsonbr** [comment]
@davidlehrian Maybe that will help you, but I'm still finalizing the development. Take a look at branch development.

And here's the link to the tests:
https://github.com/PyReportJasper/pyreportjasper/actions/runs/373524554

**Comment by davidlehrian** [comment]
@jadsonbr I like the design and can certainly adapt my code to work with it.  One thing I recently learned though is that if you are using a file stored on AWS S3 they don't work with the Python os.path commands.  I have removed references to os.path from my version of pyreportjasper and instead pass as parameters the file names I want the processor to use.  So the compile and process_report methods would both puke running on AWS with the JRXML file stored on S3.  I understand this is a specific use case, but I have had to spend a day figuring out all the issues related to it so that it will work.  

Just to give you my use case, I have a Django app running on AWS ElasticBeanstalk.  As the administrator of the site I would like to be able to add reports dynamically for my clients to be able to run.  When I upload the reports they were originally getting stored to the "media" folder on the linux file system but when the system was redeployed or scaled these files were wiped out but I still had a reference to them in my database.  So I started storing my files on AWS S3 via https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html.  This way the .jrxml files would persist when the app was redeployed or scaled.  However this broke my pyjasperreport because I was using os.path to build the .jasper file name and os.path isn't implemented for django-storage on S3 files.  Yeah yeah I'm really down a rat hole here.  So I finally fixed everything by making my application deal with file paths and removed all references to os.path from pyjasperreports.  So my application provides the path to the .jasper file which I create in the 'media' folder as it can be recreated from the .jrxml file if the system is scaled or redeployed.  I also pass in the image path which is technically a mapped url I add to the urls.py file in my Django app.  This is where JasperReports stores the images it generates when a graph is included in the report.  I hope this isn't too much information, but I wanted to provide you with some context for how I'm using JasperReports and pyreportjasper.

**Comment by Thrameos** [comment]
@davidlehrain you rang?  The list of jvm supported is limited to those available for testing on the CI system.   Jpype runs on all versions after 7 but sometimes they make changes to internal calls like the infamous jdk 12 caller sensitive bug.  Thus we can only claim support for tested jdk versions.

**Comment by jadsonbr** [comment]
@Thrameos Let me see if I got it right. Are you saying that the java used by CI may have been modified and jpype may not work correctly?

**Comment by Thrameos** [comment]
Not quite what i said.  Azure only offers certain jvms on the CI.  Thus the only jvms we know to work are those we test locally or in the CI.  To be more technical we should only list LTS releases and those are the only ones that the CI stocks. The current LTS are 8 and 11.    I keep expecting a new LTS but there hasnt been one since 11.

If a user reports a bug in any version after 7 we have attempted to addressed it.  Some like jdk 12 have bugs in the release the cause fatal problems.  In 12 all caller sensitive methods gave a null pointer exception so certain reflection and database calls failed because JNI does not count as a caller frame.  Though we did eventually find a work around  i am not aware if openjdk released a fix.  I think JVM just moved on to 13.   I am not sure if the other wrappers like jpy ever addressed this buggy release.  

In short JPype should support any version post 7.  But occasionally we have hit problems that force a new release or were do not fix if they are not LTS Java releases.  We only have one developer and one maintainer so it is best effort.

The JPype generally is more responsive than some of the other bridge codes at least while I am available in a development cycle.    I work with it daily and support a group of scientists using this in production code so I have worked to get this to the same production levels ( no leaks or faults allowed).  If you see a feature that we do not cover please put it in our issue list.  We are currently in a development cycle to add java class extension and java to python bridge capabilities.  The last feature feasta were any reasonable request is granted (30 pulls in 30 nights) was in March.

**Comment by jadsonbr** [comment]
@Thrameos Understand. Thank you for the explanation.

**Comment by Thrameos** [comment]
No problem.  If you need further info on JPype or have questions as to how to use it feel free to ping me.  

I am trying to consolidate as many of the current Python to Java bridges as possible.   Having multiple bridges just means incompatible Python modules and replicative efforts to address the same technical issues.   This has left must of the bridges covering the same area well (calling classes, methods, and fields using reflection) and left the hard parts incomplete (documentation?, extending java classes, proper termination and clean up, dealing with memory loops).   Some like Py4j server fundamentally different applications and thus not possible to consolidate.  Others like pyjnius covered exactly the same ground as JPype with just a few specialty features that needed to be addressed.  But to understand those differences I need input from the developers or the users.   Especially since most bridges are not very well documented thus determining what exactly is the differences is challenging.

JPype does not currently cover quite the same ground as jpy as it does not function as a reverse bridge, but many people are using it purely as a Python to Java bridge.  I would like to hear from any such users as to if there are any features that JPype is not currently covering.   Meanwhile I am working on the Java to Python bridge so that jpy and jep can be a good consolidation target.

**Comment by jadsonbr** [comment]
@Thrameos You can count on me

**Pull request merged**
